enableGlobalCache: true

httpTimeout: 300000

nodeLinker: node-modules

npmAuthIdent: "foo:bar"

npmRegistryServer: "http://127.0.0.1:4873/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist:
  - "localhost"
  - "127.0.0.1"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
